name: 'secret'
version: '1.0.0'
config-version: 2

profile: default

vars:
  my_cool_var: '2016-06-01'
  snowflake_meta_src_db: 'snowflake' # override this with -> dbt run --vars "'snowflake_meta_src_db': 'my_snowflake_meta_src_db'"

# on-run-start: 'CALL {{stored_proc__pi()}}();'

models:
  secret:
    +materialized: view
    
    snowflake_meta:
      +tags: ['snowflake_meta']
      +schema: snowflake_meta

    demos:
      easy_incremental:
        +materialized: easy_incremental
        +watermark: watermark
      custom_schema:
        +materialized: table
        +schema: custom_schema
      snapshots:
        +enabled: False


sources:
  secret:
    snowflake_meta:
      +tags: ['snowflake_meta']


snapshots:
  secret:
    snowflake_meta:
      +tags: ['snowflake_meta']
      +target_schema: snowflake_meta

    hard_deletes:
      +enabled: False


