
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'secret'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

vars:
  my_cool_var: '2016-06-01'
  snowflake_meta_src_db: 'snowflake' # override this with -> dbt run --vars "'snowflake_meta_src_db': 'my_snowflake_meta_src_db'"

# on-run-start: 'CALL {{stored_proc__pi()}}();'

models:
  dbt_workspace:
    +materialized: view
    hello:
      +materialized: table
      +schema: hello
    staging:
      +pre-hook: "{{validate_model_name(this, 'stage')}}"
      +post-hook: "{{validate_column_names(this)}}"
    demos:
      easy_incremental:
        +materialized: easy_incremental
        +watermark: watermark
      custom_schema:
        +materialized: table
        +schema: custom_schema

snapshots:
  secret




