name: 'secret'
version: '1.0.0'
config-version: 2

profile: default

vars:
  my_cool_var: '2016-06-01'
  snowflake_meta_src_db: 'snowflake' # override this with -> dbt run --vars "'snowflake_meta_src_db': 'my_snowflake_meta_src_db'"

# on-run-start: 'CALL {{stored_proc__pi()}}();'

models:
  secret:
    +schema: coalesce
    coalesce-2022:
      coalesce_tidy_up:
        pre-hook: '{{clean_workspace(dry_run=True)}}'
        post-hook: 'drop view {{this}}'
    secret:
      +enabled: False

sources:
  secret:
    snowflake_meta:
      +tags: ['snowflake_meta']

seeds:
  secret:
    +enabled: False # disabled because these sources are static and take a few minutes to upload.
    tpch:
      +schema: tpch
      +tags: ['tpch']
    jaffle_shop:
      +schema: jaffle
      +tags: ['jaffle']
    zodiac:
      +enabled: True
      +schema: coalesce
      +tags: ['zodiac']


snapshots:
  secret:
    +schema: coalesce

    snowflake_meta:
      +enabled: False
      +tags: ['snowflake_meta']
      +target_schema: "{{ 'snowflake_meta' if 'prod' in target.name.lower() else target.schema ~ '__snowflake_meta' }}"

    hard_deletes:
      +enabled: False


