-- This script creates several tables and grants ownership and select permissions to specific roles.
-- It also creates a new role and grants it select permissions on the tables and views in the schema.
-- Finally, it grants usage permissions on the database and warehouse to the new role.

-- Create a table to store warehouse metering history and grant ownership and select permissions.
CREATE OR REPLACE TABLE RANDY_PITCHER_WORKSPACE_DEV.STORED_PROCS_MART.WAREHOUSE_METERING_HISTORY AS (
  SELECT * 
  FROM RANDY_PITCHER_WORKSPACE_DEV.STORED_PROCS.WAREHOUSE_METERING_HISTORY
);
GRANT OWNERSHIP ON TABLE RANDY_PITCHER_WORKSPACE_DEV.STORED_PROCS_MART.WAREHOUSE_METERING_HISTORY 
	TO ROLL RANDY_PITCHER_WORKSPACE_DEV_WRITE;
GRANT SELECT ON TABLE RANDY_PITCHER_WORKSPACE_DEV.STORED_PROCS_MART.WAREHOUSE_METERING_HISTORY 
	TO ROLL RANDY_PITCHER_WORKSPACE_DEV_READ;

-- Create a table to store snowpipes and grant ownership and select permissions.
CREATE OR REPLACE TABLE RANDY_PITCHER_WORKSPACE_DEV.STORED_PROCS_MART.SNOWPIPES AS (
  SELECT *, 
    (SELECT MAX(INGESTION_TIME) FROM RANDY_PITCHER_WORKSPACE_DEV.STORED_PROCS.SNOWPIPES) AS LATEST_INGESTION_TIME, 
    INGESTION_TIME = LATEST_INGESTION_TIME AS IS_LATEST 
  FROM RANDY_PITCHER_WORKSPACE_DEV.STORED_PROCS.SNOWPIPES
);
GRANT OWNERSHIP ON TABLE RANDY_PITCHER_WORKSPACE_DEV.STORED_PROCS_MART.SNOWPIPES 
	TO ROLL RANDY_PITCHER_WORKSPACE_DEV_WRITE;
GRANT SELECT ON TABLE RANDY_PITCHER_WORKSPACE_DEV.STORED_PROCS_MART.SNOWPIPES 
	TO ROLL RANDY_PITCHER_WORKSPACE_DEV_READ;

-- Create a table to store snowpipe usage history and grant ownership and select permissions.
CREATE OR REPLACE TABLE RANDY_PITCHER_WORKSPACE_DEV.STORED_PROCS_MART.SNOWPIPE_USAGE_HISTORY AS (
  SELECT * 
  FROM RANDY_PITCHER_WORKSPACE_DEV.STORED_PROCS.SNOWPIPE_USAGE_HISTORY
);
GRANT OWNERSHIP ON TABLE RANDY_PITCHER_WORKSPACE_DEV.STORED_PROCS_MART.SNOWPIPE_USAGE_HISTORY 
	TO ROLL RANDY_PITCHER_WORKSPACE_DEV_WRITE;
GRANT SELECT ON TABLE RANDY_PITCHER_WORKSPACE_DEV.STORED_PROCS_MART.SNOWPIPE_USAGE_HISTORY 
	TO ROLL RANDY_PITCHER_WORKSPACE_DEV_READ;

-- Create a table to store query history and grant ownership and select permissions.
CREATE OR REPLACE TABLE RANDY_PITCHER_WORKSPACE_DEV.STORED_PROCS_MART.QUERY_HISTORY AS (
  SELECT * 
  FROM RANDY_PITCHER_WORKSPACE_DEV.STORED_PROCS.QUERY_HISTORY
);
GRANT OWNERSHIP ON TABLE RANDY_PITCHER_WORKSPACE_DEV.STORED_PROCS_MART.QUERY_HISTORY 
	TO ROLL RANDY_PITCHER_WORKSPACE_DEV_WRITE;
GRANT SELECT ON TABLE RANDY_PITCHER_WORKSPACE_DEV.STORED_PROCS_MART.QUERY_HISTORY 
	TO ROLL RANDY_PITCHER_WORKSPACE_DEV_READ;

-- Create a table to store tasks and grant ownership and select permissions.
CREATE OR REPLACE TABLE RANDY_PITCHER_WORKSPACE_DEV.STORED_PROCS_MART.TASKS AS (
  SELECT *, 
    (SELECT MAX(INGESTION_TIME) FROM RANDY_PITCHER_WORKSPACE_DEV.STORED_PROCS.TASKS) AS LATEST_INGESTION_TIME, 
    INGESTION_TIME = LATEST_INGESTION_TIME AS IS_LATEST 
  FROM RANDY_PITCHER_WORKSPACE_DEV.STORED_PROCS.TASKS
);
GRANT OWNERSHIP ON TABLE RANDY_PITCHER_WORKSPACE_DEV.STORED_PROCS_MART.TASKS 
	TO ROLL RANDY_PITCHER_WORKSPACE_DEV_WRITE;
GRANT SELECT ON TABLE RANDY_PITCHER_WORKSPACE_DEV.STORED_PROCS_MART.TASKS 
	TO ROLL RANDY_PITCHER_WORKSPACE_DEV_READ;

-- Create a table to store task usage history and grant ownership and select permissions.
CREATE OR REPLACE TABLE RANDY_PITCHER_WORKSPACE_DEV.STORED_PROCS_MART.TASK_USAGE_HISTORY AS (
  SELECT * 
  FROM RANDY_PITCHER_WORKSPACE_DEV.STORED_PROCS.TASK_USAGE_HISTORY
);
GRANT OWNERSHIP ON TABLE RANDY_PITCHER_WORKSPACE_DEV.STORED_PROCS_MART.TASK_USAGE_HISTORY 
	TO ROLL RANDY_PITCHER_WORKSPACE_DEV_WRITE;
GRANT SELECT ON TABLE RANDY_PITCHER_WORKSPACE_DEV.STORED_PROCS_MART.TASK_USAGE_HISTORY 
	TO ROLL RANDY_PITCHER_WORKSPACE_DEV_READ;

-- Create a table to store snowflake compute costs and grant ownership and select permissions.
CREATE OR REPLACE TABLE RANDY_PITCHER_WORKSPACE_DEV.STORED_PROCS_MART.SNOWFLAKE_COST AS (
  SELECT 'Snowflake Compute' AS SERVICE, 
    SUM(CREDITS_USED) * 3.00 AS COST, 
    START_TIME::DATE AS START_DATE 
  FROM RANDY_PITCHER_WORKSPACE_DEV.STORED_PROCS_MART.WAREHOUSE_METERING_HISTORY
);
GRANT OWNERSHIP ON TABLE RANDY_PITCHER_WORKSPACE_DEV.STORED_PROCS_MART

.SNOWFLAKE_COST 
	TO ROLL RANDY_PITCHER_WORKSPACE_DEV_WRITE;
GRANT SELECT ON TABLE RANDY_PITCHER_WORKSPACE_DEV.STORED_PROCS_MART.SNOWFLAKE_COST 
	TO ROLL RANDY_PITCHER_WORKSPACE_DEV_READ;

-- Create a new role and grant it select permissions on the schema, views, and tables.
CREATE ROLE IF NOT EXISTS RANDY_PITCHER_WORKSPACE_DEV_STORED_PROCS_MART_READ_ROLE;
GRANT ROLE RANDY_PITCHER_WORKSPACE_DEV_STORED_PROCS_MART_READ_ROLE 
	TO ROLL SYSADMIN; -- always do this
GRANT USAGE ON DATABASE RANDY_PITCHER_WORKSPACE_DEV 
	TO ROLL RANDY_PITCHER_WORKSPACE_DEV_STORED_PROCS_MART_READ_ROLE;
GRANT USAGE ON SCHEMA RANDY_PITCHER_WORKSPACE_DEV.STORED_PROCS_MART 
	TO ROLL RANDY_PITCHER_WORKSPACE_DEV_STORED_PROCS_MART_READ_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA RANDY_PITCHER_WORKSPACE_DEV.STORED_PROCS_MART 
	TO ROLL RANDY_PITCHER_WORKSPACE_DEV_STORED_PROCS_MART_READ_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA RANDY_PITCHER_WORKSPACE_DEV.STORED_PROCS_MART 
	TO ROLL RANDY_PITCHER_WORKSPACE_DEV_STORED_PROCS_MART_READ_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA RANDY_PITCHER_WORKSPACE_DEV.STORED_PROCS_MART 
	TO ROLL RANDY_PITCHER_WORKSPACE_DEV_STORED_PROCS_MART_READ_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RANDY_PITCHER_WORKSPACE_DEV.STORED_PROCS_MART 
	TO ROLL RANDY_PITCHER_WORKSPACE_DEV_STORED_PROCS_MART_READ_ROLE;
GRANT SELECT ON ALL MATERIALIZED VIEWS IN SCHEMA RANDY_PITCHER_WORKSPACE_DEV.STORED_PROCS_MART 
	TO ROLL RANDY_PITCHER_WORKSPACE_DEV_STORED_PROCS_MART_READ_ROLE;
GRANT SELECT ON FUTURE MATERIALIZED VIEWS IN SCHEMA RANDY_PITCHER_WORKSPACE_DEV.STORED_PROCS_MART 
	TO ROLL RANDY_PITCHER_WORKSPACE_DEV_STORED_PROCS_MART_READ_ROLE;